project_id = "lrvgennjbmmbtpywloem"

[functions.donations-api]
verify_jwt = false

[functions.volunteer-api]
verify_jwt = false

[functions.matching-engine]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.analytics]
verify_jwt = false